// Generated by CoffeeScript 1.3.3
(function() {
  var MainVisual, Top;

  Top = (function() {

    Top.prototype.mainVisual = null;

    function Top() {
      if ($('#slideshow').length) {
        this.mainVisual = new MainVisual($('#slideshow'));
      }
    }

    return Top;

  })();

  MainVisual = (function() {

    MainVisual.prototype.INTERVAL_TIME = 7000;

    MainVisual.prototype.currentIndex = null;

    MainVisual.prototype.max = 0;

    MainVisual.prototype.target = null;

    MainVisual.prototype.slideimageContainer = null;

    MainVisual.prototype.slideimage = null;

    MainVisual.prototype.nav = null;

    MainVisual.prototype.intervalId = null;

    function MainVisual(target) {
      var _this = this;
      this.target = target;
      _this = this;
      this.slideimageContainer = this.target.find('.slideimage');
      this.slideimage = this.target.find('.slideimage li');
      this.max = this.slideimage.length;
      this.nav = this.target.find('.slidenav li a');
      this.nav.on({
        click: function() {
          var index;
          index = $(this).parent().index();
          _this.change(index);
          return false;
        }
      });
      setTimeout(function() {
        return _this.change(0);
      }, 1000);
    }

    MainVisual.prototype.startInterval = function() {
      var _this = this;
      this.stopInterval();
      return this.intervalId = setTimeout(function() {
        return _this.next();
      }, this.INTERVAL_TIME);
    };

    MainVisual.prototype.stopInterval = function() {
      if (this.intervalId) {
        return clearInterval(this.intervalId);
      }
    };

    MainVisual.prototype.changeNav = function(index) {
      return this.nav.each(function(i) {
        var img, src;
        img = $(this).find('img');
        src = img.attr('src');
        if (index === i) {
          $(this).parent().addClass('active');
          src = src.replace('-off.png', '-on.png');
          return img.attr('src', src);
        } else {
          $(this).parent().removeClass('active');
          src = src.replace('-on.png', '-off.png');
          return img.attr('src', src);
        }
      });
    };

    MainVisual.prototype.next = function() {
      var next;
      next = this.currentIndex + 1;
      if (next >= this.max) {
        next = 0;
      }
      return this.change(next);
    };

    MainVisual.prototype.change = function(index) {
      var tmp;
      if (this.currentIndex === index) {
        return;
      }
      this.changeNav(index);
      this.currentIndex = index;
      tmp = $(this.slideimage.get(index));
      tmp.css({
        opacity: 0,
        visibility: 'visible'
      });
      this.slideimageContainer.append(tmp);
      tmp.stop().animate({
        opacity: 1
      }, 1400, 'easeOutCubic');
      return this.startInterval();
    };

    return MainVisual;

  })();

  $(function() {
    return new Top();
  });

}).call(this);
